version: '3.3'

services:
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  db:
    image: pgrouting/pgrouting:12-3.0-3.0.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "4321:5432"
    env_file:
      - ./.env.prod.db
volumes: 
  postgres_data:
