# Generated by Django 3.2 on 2021-11-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_auto_20211021_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='x1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='y1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='y2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
