# Generated by Django 3.2 on 2021-10-21 23:46

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension("pgrouting"),
    ]
